### ISSUE TITLE
Add wildcard support

### ISSUE THREAD

**Issue by ruler501** [Gelio/loose-ts-check#9]
It would be great to have wildcard support for paths. Ultimately what I'm trying to accomplish is ignoring errors from inside node_modules. A library I use hasn't migrated to a full strict tsconfig and ship ts files so I get errors from that. See https://github.com/solidjs/solid-start/issues/255 for more specifics. 

Since I'm using pnpm the file paths change everytime I update the package so it causes a lot of churn of the `loosely-type-checked-files.json` file and has become a chore to maintain since we have to verify that none of our files have errors before running `--auto-update`.

**Comment by Gelio** [comment]
Hey, thanks for your interest in this tool and for a feature request!

I've added wildcard support in [the recently released v1.3.0](https://github.com/Gelio/loose-ts-check/releases/tag/v1.3.0). Let me know if it works for you.

You should be able to add `node_modules/**/*` to `loosely-type-checked-files.json` to have `loose-ts-check` ignore all errors from `node_modules`

**Comment by ruler501** [comment]
This is exactly what I needed. Works great thank you very much.

**Comment by Gelio** [comment]
Great, I'm glad it works well :ok_hand:
